import {store} from "@/store.js";

const state = store.getState();
const language = state.settings.language;

const translations = {
    en: {
        LoadMusic: "Load music",
        NewAlbum: "New album",
        AddMusic: "Add music",
        Select: "Select",
        Delete: "Delete",
        Share: "Share",
        Remove: "Remove",
        Music: "Music",
        Albums: "Albums",
        Settings: "Settings",
        ConfirmDeleting: "Are you sure?",
        Cancel: "Cancel",
        Add: "Add",
        AlbumName: "Album name",
        AddMusicFirst: "Add music first",
        ChooseAlbum: "Choose album to play",
        AllMusicAlreadyInAlbum: "All music already in album",
        ShowJumpControls: "Show jump controls",
        Language: "Language",
        Theme: "Theme",
        CopiedToClipBoard: "Copied to clipboard",
        Login: "Login",
        Password: "Password",
        ShowPassword: "Show password",
        LoginOrPasswordIsIncorrect: "Login or password is incorrect",
        LogIn: "Log in",
        Registration: "Registration",
        CreateLogin: "Create login",
        PickPassword: "Pick password",
        LoginShouldBeLonger: "Login should be longer",
        PasswordShouldBeLonger: "Password should be longer",
        LoginAlreadyExist: "Login already exist",
        CreateAccount: "Create account",
        SearchMusic: "Search music",
        ChangeLogin: "Change login",
        ChangePassword: "Change password",
        NewLogin: "New login",
        NewPassword: "New password",
        ConfirmPassword: "Confirm password",
        DeleteAccount: "Delete account",
        On: "On",
        Off: "Off",
        Save: "Save",
        Light: "Light",
        Dark: "Dark",
        Gray: "Gray",
        Neon: "Neon",
        Songs: "songs",
    },
    uk: {
        LoadMusic: "Завантажити музику",
        NewAlbum: "Новий альбом",
        AddMusic: "Додати музику",
        Select: "Обрати",
        Delete: "Видалити",
        Share: "Поділитися",
        Remove: "Прибрати",
        Music: "Музика",
        Albums: "Альбоми",
        Settings: "Налаштування",
        ConfirmDeleting: "Ви впевнені?",
        Cancel: "Відмінити",
        Add: "Додати",
        AlbumName: "Ім'я альбому",
        AddMusicFirst: "Спочатку додайте музику",
        ChooseAlbum: "Виберіть альбом для програвання",
        AllMusicAlreadyInAlbum: "Вся музика вже в альбомі",
        ShowJumpControls: "Показувати перемотувачі",
        Language: "Мова",
        Theme: "Тема",
        CopiedToClipBoard: "Скопійовано в буфер обміну",
        Login: "Логін",
        Password: "Пароль",
        ShowPassword: "Показувати пароль",
        LoginOrPasswordIsIncorrect: "Логін чи пароль невірні",
        LogIn: "Вхід",
        Registration: "Реєстрація",
        CreateLogin: "Створіть логін",
        PickPassword: "Підберіть пароль",
        LoginShouldBeLonger: "Логін має бути довшим",
        PasswordShouldBeLonger: "Пароль має бути довшим",
        LoginAlreadyExist: "Логін вже існує",
        CreateAccount: "Створити аккаунт",
        SearchMusic: "Пошук музики",
        ChangeLogin: "Зміна логіну",
        ChangePassword: "Зміна паролю",
        NewLogin: "Новий логін",
        NewPassword: "Новий пароль",
        ConfirmPassword: "Підтвердження паролю",
        DeleteAccount: "Видалити аккаунт",
        On: "Ввімк",
        Off: "Вимк",
        Save: "Зберегти",
        Light: "Світла",
        Dark: "Темна",
        Gray: "Сіра",
        Neon: "Неонова",
        Songs: "пісень",
    },
};

export const translation = translations[language] || translations["en"];
